# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2504814c8e5bd839f0d1aa66deb179d1e40c54ef704283a089ca6bd47dd3bfca99edff6866c107f111585d5778c1b2183d912e63dc60cfc8a6a92a1c4d36635

test:
  secret_key_base: 9eb89b9c4f0237685953434059f47a8903422d952ca4d73c7b6b153be0cebaac8c38e3b02292d277721d53634d80ced9fbaee40cfb9f162e2f05ab872a9a7377

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
